# Choleskey Factorization

In this section we develop Python code to solve linear systems whose coefficent matrix is positive definite, via **Cholesky Factorization.**

Recall that an $n\times n$ matrix $A$ is postive definite if and only if $A$ can be factored in the form $LL^T$, where $L$ is lower triangular with nonzero diagonal entries.



In [9]:
import sys
import math
import numpy as np

In [10]:
import sys
import math
import numpy as np

def cholesky(A):
# =============================================================================
#     A is an nxn matrix .
#     indicies counting from 1 (not as in python).
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    if m != n:
        print("Square matrix not provided.\n")
        print("m = ",m)
        print("n = ",n)
        return

    L = np.zeros((n,n))

    # visit each row from i = 2 to i = n
    L[0][0] = math.sqrt(A[0][0])
    for i in range(1,n):
        L[i][0] = A[i][0] / L[0][0]

    for j in range(1,n-1):
        L[j][j] = math.sqrt( A[j][j] - sum((L[j][0:j])**2) )

        for i in range(j+1,n):
            L[i][j] = (A[i][j] - sum(L[i][0:j] * L[j][0:j])) / L[j][j]

    L[n-1][n-1] = math.sqrt( A[n-1][n-1] - sum((L[n-1][0:n-1])**2) )

    return L

In [11]:
L = cholesky(A)

13. Find the Cholesky factorization $A = LL^T$ for each of the following matrices by hand. Check your results with output generated from your code in problem 12.

(a)
$\begin{bmatrix}
  1 & 2 \\
  2 & 8
\end{bmatrix}$

In [12]:
# Define a sample positive definite matrix A
A = np.array([[1, 2], [2, 8]])

# Call the cholesky function with A
L = cholesky(A)

# Display the resulting lower triangular matrix L
print("Matrix A:")
print(A)
print("\nLower triangular matrix L:")
print(L)

# Verify the result by computing LL^T
print("\nVerification (LL^T):")
print(np.dot(L, L.T))

Matrix A:
[[1 2]
 [2 8]]

Lower triangular matrix L:
[[1. 0.]
 [2. 2.]]

Verification (LL^T):
[[1. 2.]
 [2. 8.]]


(b)
$\begin{bmatrix}
  4 & -2 \\
  -2 & 5/4
\end{bmatrix}$

In [13]:
# Define a sample positive definite matrix A
A = np.array([[4, -1], [-2, 5/4]])

# Call the cholesky function with A
L = cholesky(A)

# Display the resulting lower triangular matrix L
print("Matrix A:")
print(A)
print("\nLower triangular matrix L:")
print(L)

# Verify the result by computing LL^T
print("\nVerification (LL^T):")
print(np.dot(L, L.T))

Matrix A:
[[ 4.   -1.  ]
 [-2.    1.25]]

Lower triangular matrix L:
[[ 2.   0. ]
 [-1.   0.5]]

Verification (LL^T):
[[ 4.   -2.  ]
 [-2.    1.25]]


(c)
$\begin{bmatrix}
  4 & -2 & 0 \\
  -2 & 2 & -3 \\
  0 & -3 & 10
\end{bmatrix}$

In [14]:
# Define a sample positive definite matrix A
A = np.array([[4, -2, 0], [-2, 2, -3], [0, -3, 10]])

# Call the cholesky function with A
L = cholesky(A)

# Display the resulting lower triangular matrix L
print("Matrix A:")
print(A)
print("\nLower triangular matrix L:")
print(L)

# Verify the result by computing LL^T
print("\nVerification (LL^T):")
print(np.dot(L, L.T))

Matrix A:
[[ 4 -2  0]
 [-2  2 -3]
 [ 0 -3 10]]

Lower triangular matrix L:
[[ 2.  0.  0.]
 [-1.  1.  0.]
 [ 0. -3.  1.]]

Verification (LL^T):
[[ 4. -2.  0.]
 [-2.  2. -3.]
 [ 0. -3. 10.]]


(d)
$\begin{bmatrix}
  1 & 2 & 0 \\
  2 & 5 & 2 \\
  0 & 2 & 5
\end{bmatrix}$

In [16]:
# Define a sample positive definite matrix A
A = np.array([[1, 2, 0], [2, 5, 2], [0, 2, 5]])

# Call the cholesky function with A
L = cholesky(A)

# Display the resulting lower triangular matrix L
print("Matrix A:")
print(A)
print("\nLower triangular matrix L:")
print(L)

# Verify the result by computing LL^T
print("\nVerification (LL^T):")
print(np.dot(L, L.T))

Matrix A:
[[1 2 0]
 [2 5 2]
 [0 2 5]]

Lower triangular matrix L:
[[1. 0. 0.]
 [2. 1. 0.]
 [0. 2. 1.]]

Verification (LL^T):
[[1. 2. 0.]
 [2. 5. 2.]
 [0. 2. 5.]]
